class LeakProfiler
  def initialize: (?output_dir: String) -> void

  # TODO: Use valid type for logger
  def report: (?interval: Integer, ?max_allocations: Integer, ?max_referrers: Integer, ?logger: Object, ?filename: String) -> self

  def report_rss: (?interval: Integer, ?filename: String) -> self

  def report_memsize: (?interval: Integer, ?filename: String) -> self
end
