name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read

env:
  TESTOPTS: --verbose

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.1

  lint:
    runs-on: ubuntu-latest

    name: RuboCop
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 4.0
        bundler-cache: true
    - uses: r7kamura/rubocop-problem-matchers-action@v1
    - run: bundle exec rubocop --parallel

  rbs:
    runs-on: ubuntu-latest

    name: Check RBS
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0
          bundler-cache: true
      - name: Check RBS signatures are properly updated
        run: |
          bundle exec rake rbs:update
          git --no-pager diff --exit-code
          bundle exec steep check

  test:
    needs: ruby-versions
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - ruby: head
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
